default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: agendamento_vacina_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: postgres
  port: 5432

test:
  <<: *default
  encoding: utf8
  timeout: 5000
  database: agendamento_vacina_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: postgres
  port: 5432

production:
  <<: *default
  database: agendamento_vacina_production
  username: agendamento_vacina
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
